#define IDD_LOCATIONNAVIGATE    2500
                                
#define ID_UGO_STATIC           (IDD_LOCATIONNAVIGATE + 1)
#define ID_LNHISTORY_EDIT       (IDD_LOCATIONNAVIGATE + 2)
#define IDC_LOC_LIST            (IDD_LOCATIONNAVIGATE + 4)
#define ID_UGO_STATIC2          (IDD_LOCATIONNAVIGATE + 5)
#define ID_LNHISTORY_EDIT2      (IDD_LOCATIONNAVIGATE + 6)
#define IDC_STATIC_ABOUT        (IDD_LOCATIONNAVIGATE + 7)
#define IDC_CHECK_AUTO          (IDD_LOCATIONNAVIGATE + 8)
#define IDC_BUTTON_CLEAR        (IDD_LOCATIONNAVIGATE + 9)
#define IDC_CHECK_ALWAYS        (IDD_LOCATIONNAVIGATE + 10)
#define IDC_CHECK_SAVERECORD    (IDD_LOCATIONNAVIGATE + 11)
#define IDC_CHECK_INCURR        (IDD_LOCATIONNAVIGATE + 12)
#define IDC_CHECK_MARK          (IDD_LOCATIONNAVIGATE + 13)
#define ID_STATIC_COLOR         (IDD_LOCATIONNAVIGATE + 14)
#define IDC_CHECK_BOOKMARK      (IDD_LOCATIONNAVIGATE + 15)
#define ID_STATIC_SAVECOLOR     (IDD_LOCATIONNAVIGATE + 16)

#define IDB_BITMAP1              2601
#define IDB_BITMAP2              2602
#define IDB_BITMAP3              2603
#define IDB_BITMAP4              2604

#define IDI_ICON1                2605
